### ISSUE TITLE
Please fix compiler warnings

### ISSUE THREAD

**Issue by Jingjok86** [arkhipenko/TaskScheduler#87] opened 2020-02-20 17:09 UTC
Hi,
First let me say, thank you for the TaskScheduler library, really useful with powerful functionality.

As a minor issue, could you please though fix the compiler warnings about unused variables, it makes it more difficult to spot local project warnings. The warnings I get with the newest library version are :

TaskScheduler.h: In member function 'bool Scheduler::execute()':
TaskScheduler.h:904:19: warning: variable 'tStart' set but not used [-Wunused-but-set-variable]
     unsigned long tStart, tFinish;
TaskScheduler.h:904:27: warning: variable 'tFinish' set but not used [-Wunused-but-set-variable]
     unsigned long tStart, tFinish;
TaskScheduler.h:909:19: warning: unused variable 'tIdleStart' [-Wunused-variable]
     unsigned long tIdleStart = 0;

I have set only one define :
#define _TASK_TIMECRITICAL

**Comment by arkhipenko** [comment] 2020-02-23 04:52
Please test v3.1.4 from the testing branch.

**Comment by Jingjok86** [comment] 2020-02-23 13:04
Hi Anatoli,

still the same warnings in the code from the testing branch.

What fixes it is using only condition #ifdef _TASK_SLEEP_ON_IDLE_RUN 
instead of the condition
    #if defined (_TASK_SLEEP_ON_IDLE_RUN) || defined (_TASK_TIMECRITICAL)

i.e.
    #ifdef _TASK_SLEEP_ON_IDLE_RUN
        unsigned long tStart, tFinish;
    #endif
...
    #ifdef _TASK_SLEEP_ON_IDLE_RUN
        tStart = micros();  // Scheduling full pass start time in microseconds. 
    #endif
...
    #ifdef _TASK_SLEEP_ON_IDLE_RUN
        tFinish = micros(); // Scheduling pass end time in microseconds.
    #endif

because both variables are only used in line 1060, if _TASK_SLEEP_ON_IDLE_RUN is defined.

**Comment by arkhipenko** [comment] 2020-02-23 14:36
Hmm. Shooting in the dark here as I don't get those messages... Ok. Let me check again.

**Comment by arkhipenko** [comment] 2020-02-23 16:36
Please try now and retest the testing branch version 3.1.4

**Comment by Jingjok86** [comment] 2020-02-24 12:24
Hi,
OK, almost there, one warning about tIdleStart remaining, it can be fixed by changing line 924 and the next few from :

```
#ifdef _TASK_TIMECRITICAL
    register unsigned long tPassStart;
    register unsigned long tTaskStart, tTaskFinish;
    unsigned long tIdleStart = 0;
#endif  // _TASK_TIMECRITICAL
```

To :

```
#ifdef _TASK_TIMECRITICAL
    register unsigned long tPassStart;
    register unsigned long tTaskStart, tTaskFinish;
#endif 

#if defined (_TASK_SLEEP_ON_IDLE_RUN) && defined (_TASK_TIMECRITICAL)
    unsigned long tIdleStart = 0;
#endif
```

I am btw using ESP32 Arduino core on Visual Studio Code and Platform IO with default compiler warning settings, so the warnings should come up for all users with this fairly common setup.

**Comment by arkhipenko** [comment] 2020-02-25 01:59
Ok. Third time is a charm. Please try now.

**Comment by Jingjok86** [comment] 2020-02-25 13:57
Hi,
for my use case it is fine now, no compiler warnings anymore, I use only _TASK_TIMECRITICAL

But I would recommend to change line 928 from

```
#ifdef _TASK_SLEEP_ON_IDLE_RUN
```

to

```
#if defined (_TASK_SLEEP_ON_IDLE_RUN) && defined (_TASK_TIMECRITICAL)
```

as per my last post, because else users that use only the flag _TASK_SLEEP_ON_IDLE_RUN without _TASK_TIMECRITICAL will still get the warning about tIdleStart

anyway, you can close the issue, thanks !

**Comment by GitMoDu** [comment] 2020-04-01 12:22
> TaskSchedulerDeclarations.h:267: note  type struct Scheduler itself violates the C++ One Definition Rule.

This is new.

**Comment by arkhipenko** [comment] 2020-04-01 16:58
Line 267 is `#endif  // _TASK_LTS_POINTER`
???

**Comment by arkhipenko** [comment] 2020-04-01 16:59
It must be giving reference to the file resulting from a combination of several `#defines...` tho.
How can I get to your line count?  :))))

**Comment by GitMoDu** [comment] 2020-04-05 14:34
Just pulled the latest update, still get the same warning.
The line indicated is the declaration of Scheduler class.

> class Scheduler {
>   friend class Task;
>   public:

I'm using _TASK_OO_CALLBACKS and _TASK_SLEEP_ON_IDLE_RUN. If I remove the _TASK_SLEEP_ON_IDLE_RUN, then the warning doesn't appear.

**Comment by arkhipenko** [comment] 2020-04-07 16:09
What is wrong with this statement? And why did it become a warning suddenly?
I am not sure what I should do here.

**Comment by GitMoDu** [comment] 2020-04-11 14:29
> And why did it become a warning suddenly?

Probably because of Arduino's compiler version update, which is becoming more strict. I'll let you know what I find.

**Comment by GitMoDu** [comment] 2020-04-24 15:58
Ok, so PVS static analyser found nothing, but I'm still getting the warning.
I did find a [similar issue](https://stackoverflow.com/questions/40659435/one-definition-rule-warning), where in the accepted answer we can find:
> implicitly-defined inline constructor

So something to do with the inline constructors. Since this warning goes away if I disable _TASK_SLEEP_ON_IDLE_RUN, then where there's smoke there's fire.

**Comment by arkhipenko** [comment] 2020-04-24 18:08
Is it possible that this is caused by a name clash with another library? Afterall "Task" and such a common term.
I am asking because I am on the latest Arduino IDE and I do not get this warning.

**Comment by MikeBlueIce** [comment] 2020-04-26 07:42
I get  "multiple definition of iSleepMethod" and "multiple definition of iSleepScheduler"  with _TASK_SLEEP_ON_IDLE_RUN defined and multiple cpp files referencing to taskscheduler.

**Comment by GitMoDu** [comment] 2020-04-27 16:47
[Related.](https://github.com/jrowberg/i2cdevlib/issues/424)

Seems like it's Visual Micro (which I use) that's issuing that warning.

**Comment by arkhipenko** [comment] 2020-05-04 21:12
I installed Visual Micro and compiled a TS-based project with sketch and library warnings enabled - did not get this message.  Don't know what to do so I am going to close this issues.

**Closed by arkhipenko** 2020-05-04 21:12 UTC
